### ISSUE TITLE
Publish WebResources via GitHub Pages

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_datasets#10]
INCLUDES

- [x] Update dct:hasFormat values (URLs)
- [x] Place serializations in top-level directory
- [x] DOI update (metadata and URL)

**Comment by cspayne** [comment]
see [v1-1-0 commit](https://github.com/uwlib-cams/uwlswd_datasets/commit/4d275a6f3599022f928fab34a74f649060e48892)
