### ISSUE TITLE
Publish Aggregations via GitHub Pages

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_datasets#6]
INCLUDES

- [x] Update dct:hasFormat values (URLs)
- [x] Place serializations in top-level directory
- [x] DOI update (metadata and URL)

**Comment by cspayne** [comment]
see [v1-1-0 commit](https://github.com/uwlib-cams/uwlswd_datasets/commit/4499b3270ace760fdda6e446aaf78eb8bee026f7)
