### ISSUE TITLE
Publish Collections via GitHub Pages

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_datasets#7]
INCLUDES

- [ ] Update dct:hasFormat values (URLs)
- [ ] Place serializations in top-level directory
- [ ] DOI update (metadata and URL)

**Comment by briesenberg07** [comment]
If possible include work for #2 here

**Comment by cspayne** [comment]
see [v1-1-0 commit](https://github.com/uwlib-cams/uwlswd_datasets/commit/066cf9f5d09f2291a266e0994ed34405d27abdea)
