### ISSUE TITLE
Publish RightsStatements via GitHub Pages

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_datasets#8]
INCLUDES

- [x] Update dct:hasFormat values (URLs)
- [x] Place serializations in top-level directory
- [x] DOI update (metadata and URL)

**Comment by cspayne** [comment]
see [v1-1-0 commit](https://github.com/uwlib-cams/uwlswd_datasets/commit/47e6b711a8e836c9ed069328a2ffdfe1fce0da21)
