### ISSUE TITLE
Publish SourceResources via GitHub Pages

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_datasets#9]
INCLUDES

- [x] Update dct:hasFormat values (URLs)
- [x] Place serializations in top-level directory
- [x] DOI update (metadata and URL)

**Comment by cspayne** [comment]
see [v1-1-0 commit](https://github.com/uwlib-cams/uwlswd_datasets/commit/9e5fb9ba4d8675d0cd5b6508714073f2a827a9ff)
